apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: https-proxy-mod
  namespace: kube-system
  labels:
    tier: management
    app: https-proxy-mod
spec:
  selector:
    matchLabels:
      name: https-proxy-mod
  template:
    metadata:
      labels:
        name: https-proxy-mod
    spec:
      initContainers:
        - command: ["/bin/sh", "-c"]
          args:
            - >
              echo NO_PROXY="${cluster_local},cluster.local,.svc,localhost,127.0.0.1,172.20.0.1,172.21.0.0/16,172.17.0.0/18,161.26.0.0/16,166.8.0.0/14,172.20.0.0/16"  > /host/etc/sysconfig/${crio-config-file};
              echo HTTP_PROXY="http://${proxy_ip}:${proxy_port}/" >> /host/etc/sysconfig/${crio-config-file};
              echo HTTPS_PROXY="http://${proxy_ip}:${proxy_port}/" >> /host/etc/sysconfig/${crio-config-file};
          image: ${ocp_release_dev_image}
          imagePullPolicy: IfNotPresent
          name: crio-proxy-setup
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - name: host
              mountPath: /host
      containers:
        - resources:
            requests:
              cpu: 10m
          image: ${ocp_release_dev_image}
          command: ["/bin/sh", "-c"]
          name: pause
          args:
            - >
              while true; do
                sleep 100000;
              done
      tolerations:
      - operator: Exists
      volumes:
        - name: host
          hostPath:
            path: /
            type: Directory
